In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

In [66]:
file_path="winequality_red.csv"
df=pd.read_csv(file_path)
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               NaN               NaN          NaN             NaN        NaN   
1               7.4             0.700         0.00             1.9      0.076   
2               NaN               NaN          NaN             NaN        NaN   
3               7.8             0.880         0.00             2.6      0.098   
4               NaN               NaN          NaN             NaN        NaN   
...             ...               ...          ...             ...        ...   
3193            6.3             0.510         0.13             2.3      0.076   
3194            NaN               NaN          NaN             NaN        NaN   
3195            5.9             0.645         0.12             2.0      0.075   
3196            NaN               NaN          NaN             NaN        NaN   
3197            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                     NaN                   NaN      NaN   NaN        NaN   
1                    11.0                  34.0  0.99780  3.51       0.56   
2                     NaN                   NaN      NaN   NaN        NaN   
3                    25.0                  67.0  0.99680  3.20       0.68   
4                     NaN                   NaN      NaN   NaN        NaN   
...                   ...                   ...      ...   ...        ...   
3193                 29.0                  40.0  0.99574  3.42       0.75   
3194                  NaN                   NaN      NaN   NaN        NaN   
3195                 32.0                  44.0  0.99547  3.57       0.71   
3196                  NaN                   NaN      NaN   NaN        NaN   
3197                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         NaN      NaN  
1         9.4      5.0  
2         NaN      NaN  
3         9.8      5.0  
4         NaN      NaN  
...       ...      ...  
3193     11.0      6.0  
3194      NaN      NaN  
3195     10.2      5.0  
3196      NaN      NaN  
3197     11.0      6.0  

[3198 rows x 12 columns]

In [67]:
df.dropna(inplace=True,axis=0)

In [68]:
df.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3189            6.2             0.600         0.08             2.0      0.090   
3191            5.9             0.550         0.10             2.2      0.062   
3193            6.3             0.510         0.13             2.3      0.076   
3195            5.9             0.645         0.12             2.0      0.075   
3197            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3189                 32.0                  44.0  0.99490  3.45       0.58   
3191                 39.0                  51.0  0.99512  3.52       0.76   
3193                 29.0                  40.0  0.99574  3.42       0.75   
3195                 32.0                  44.0  0.99547  3.57       0.71   
3197                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
3189     10.5      5.0  
3191     11.2      6.0  
3193     11.0      6.0  
3195     10.2      5.0  
3197     11.0      6.0

In [69]:
df.shape

(1599, 12)

In [7]:
df.columns

Index(['index', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [8]:
df.isnull().sum()

index                   0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [9]:
df.dtypes

index                     int64
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                 float64
dtype: object

In [10]:
# weneed to perform EDA
# but we have numerical data (EDA means convert categorical data into numerical)

$ step-3$

*data divide into input and output*

In [11]:
df.columns

Index(['index', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [72]:
x=df.drop('quality',axis=1)
y=df['quality']

In [73]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,
                                                 y,
                                                 random_state=1234,
                                                 test_size=0.30)

In [74]:
x_train.shape, x_test.shape


((1119, 11), (480, 11))

In [75]:
y_train.shape, y_test.shape

((1119,), (480,))

In [16]:
x_train.ndim

2

In [17]:
x_train

index  fixed acidity  volatile acidity  citric acid  residual sugar  \
642    1285            9.9             0.540         0.45             2.3   
678    1357            8.3             0.780         0.10             2.6   
412     825            7.1             0.735         0.16             1.9   
73      147            8.3             0.675         0.26             2.1   
985    1971            7.4             0.580         0.00             2.0   
...     ...            ...               ...          ...             ...   
1228   2457            5.1             0.420         0.00             1.8   
1077   2155            8.6             0.370         0.65             6.4   
1318   2637            7.5             0.630         0.27             2.0   
723    1447            7.1             0.310         0.30             2.2   
815    1631           10.8             0.450         0.33             2.5   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
642       0.071                 16.0                  40.0  0.99910  3.39   
678       0.081                 45.0                  87.0  0.99830  3.48   
412       0.100                 15.0                  77.0  0.99660  3.27   
73        0.084                 11.0                  43.0  0.99760  3.31   
985       0.064                  7.0                  11.0  0.99562  3.45   
...         ...                  ...                   ...      ...   ...   
1228      0.044                 18.0                  88.0  0.99157  3.68   
1077      0.080                  3.0                   8.0  0.99817  3.27   
1318      0.083                 17.0                  91.0  0.99616  3.26   
723       0.053                 36.0                 127.0  0.99650  2.94   
815       0.099                 20.0                  38.0  0.99818  3.24   

      sulphates  alcohol  
642        0.62      9.4  
678        0.53     10.0  
412        0.64      9.3  
73         0.53      9.2  
985        0.58     11.3  
...         ...      ...  
1228       0.73     13.6  
1077       0.58     11.0  
1318       0.58      9.8  
723        1.62      9.5  
815        0.71     10.8  

[1119 rows x 12 columns]

In [18]:
y_train

642     5.0
678     5.0
412     5.0
73      4.0
985     6.0
       ... 
1228    7.0
1077    5.0
1318    6.0
723     5.0
815     5.0
Name: quality, Length: 1119, dtype: float64

In [19]:
y_test

688     5.0
961     5.0
726     6.0
537     6.0
1544    7.0
       ... 
1461    4.0
1591    6.0
1045    6.0
1498    6.0
42      6.0
Name: quality, Length: 480, dtype: float64

In [76]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [21]:
y_predictions=LR.predict(x_test)

In [22]:
y_predictions

array([5.16003375, 5.31953766, 5.63676143, 5.52619018, 6.32205835,
       5.37193125, 5.3719121 , 5.91871149, 5.46059174, 7.04899778,
       4.89121277, 5.17918663, 5.74106381, 5.54736268, 5.58388732,
       5.28318111, 4.89286274, 5.14001991, 6.28188786, 5.11768447,
       5.08506006, 5.91026743, 5.15683002, 5.4621841 , 5.69549208,
       6.27706905, 5.32894359, 5.53653669, 6.04632239, 5.46245841,
       4.69000624, 6.18231195, 5.20381374, 5.59886142, 5.59532988,
       5.54145688, 6.35591811, 5.19935401, 5.47422078, 5.81405986,
       5.15901727, 6.15368304, 5.6980289 , 5.37679862, 5.62456546,
       5.00325408, 4.90160543, 5.75799108, 6.35266686, 5.56118516,
       4.89973099, 5.77330403, 6.66588823, 6.1555186 , 5.35505711,
       5.07932047, 6.20786294, 5.21893484, 6.43001727, 5.2192625 ,
       5.32531268, 5.21835755, 5.05224599, 5.60678369, 5.0120603 ,
       6.17010025, 5.74020323, 6.37161258, 5.33865405, 6.06297922,
       5.73072649, 5.57753135, 5.18510358, 6.21179885, 5.53641

In [23]:
y_test.shape,y_predictions.shape

((480,), (480,))

In [24]:
x_test.iloc[1].values #list

array([1.9230e+03, 7.1000e+00, 5.6000e-01, 1.4000e-01, 1.6000e+00,
       7.8000e-02, 7.0000e+00, 1.8000e+01, 9.9592e-01, 3.2700e+00,
       6.2000e-01, 9.3000e+00])

In [25]:
x_test

index  fixed acidity  volatile acidity  citric acid  residual sugar  \
688    1377            7.7             0.660         0.04             1.6   
961    1923            7.1             0.560         0.14             1.6   
726    1453            8.1             0.720         0.09             2.8   
537    1075            8.1             0.825         0.24             2.1   
1544   3089            8.4             0.370         0.43             2.3   
...     ...            ...               ...          ...             ...   
1461   2923            6.2             0.785         0.00             2.1   
1591   3183            5.4             0.740         0.09             1.7   
1045   2091            6.9             0.440         0.00             1.4   
1498   2997            6.6             0.895         0.04             2.3   
42       85            7.5             0.490         0.20             2.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
688       0.039                  4.0                   9.0  0.99620  3.40   
961       0.078                  7.0                  18.0  0.99592  3.27   
726       0.084                 18.0                  49.0  0.99940  3.43   
537       0.084                  5.0                  13.0  0.99720  3.37   
1544      0.063                 12.0                  19.0  0.99550  3.17   
...         ...                  ...                   ...      ...   ...   
1461      0.060                  6.0                  13.0  0.99664  3.59   
1591      0.089                 16.0                  26.0  0.99402  3.67   
1045      0.070                 32.0                  38.0  0.99438  3.32   
1498      0.068                  7.0                  13.0  0.99582  3.53   
42        0.332                  8.0                  14.0  0.99680  3.21   

      sulphates  alcohol  
688        0.47      9.4  
961        0.62      9.3  
726        0.72     11.1  
537        0.77     10.7  
1544       0.81     11.2  
...         ...      ...  
1461       0.61     10.0  
1591       0.56     11.6  
1045       0.58     11.4  
1498       0.58     10.8  
42         0.90     10.5  

[480 rows x 12 columns]

In [26]:
LR.predict(x_test)

array([5.16003375, 5.31953766, 5.63676143, 5.52619018, 6.32205835,
       5.37193125, 5.3719121 , 5.91871149, 5.46059174, 7.04899778,
       4.89121277, 5.17918663, 5.74106381, 5.54736268, 5.58388732,
       5.28318111, 4.89286274, 5.14001991, 6.28188786, 5.11768447,
       5.08506006, 5.91026743, 5.15683002, 5.4621841 , 5.69549208,
       6.27706905, 5.32894359, 5.53653669, 6.04632239, 5.46245841,
       4.69000624, 6.18231195, 5.20381374, 5.59886142, 5.59532988,
       5.54145688, 6.35591811, 5.19935401, 5.47422078, 5.81405986,
       5.15901727, 6.15368304, 5.6980289 , 5.37679862, 5.62456546,
       5.00325408, 4.90160543, 5.75799108, 6.35266686, 5.56118516,
       4.89973099, 5.77330403, 6.66588823, 6.1555186 , 5.35505711,
       5.07932047, 6.20786294, 5.21893484, 6.43001727, 5.2192625 ,
       5.32531268, 5.21835755, 5.05224599, 5.60678369, 5.0120603 ,
       6.17010025, 5.74020323, 6.37161258, 5.33865405, 6.06297922,
       5.73072649, 5.57753135, 5.18510358, 6.21179885, 5.53641

In [27]:
x_test.iloc[1] # its is a series
# in order to pass a test sample to a model
# or array of values
#tuple of values
x_test.iloc[0].values

array([1.377e+03, 7.700e+00, 6.600e-01, 4.000e-02, 1.600e+00, 3.900e-02,
       4.000e+00, 9.000e+00, 9.962e-01, 3.400e+00, 4.700e-01, 9.400e+00])

In [28]:
LR.predict([x_test.iloc[0].values,
           x_test.iloc[1].values])

array([5.16003375, 5.31953766])

In [29]:
y_predictions

array([5.16003375, 5.31953766, 5.63676143, 5.52619018, 6.32205835,
       5.37193125, 5.3719121 , 5.91871149, 5.46059174, 7.04899778,
       4.89121277, 5.17918663, 5.74106381, 5.54736268, 5.58388732,
       5.28318111, 4.89286274, 5.14001991, 6.28188786, 5.11768447,
       5.08506006, 5.91026743, 5.15683002, 5.4621841 , 5.69549208,
       6.27706905, 5.32894359, 5.53653669, 6.04632239, 5.46245841,
       4.69000624, 6.18231195, 5.20381374, 5.59886142, 5.59532988,
       5.54145688, 6.35591811, 5.19935401, 5.47422078, 5.81405986,
       5.15901727, 6.15368304, 5.6980289 , 5.37679862, 5.62456546,
       5.00325408, 4.90160543, 5.75799108, 6.35266686, 5.56118516,
       4.89973099, 5.77330403, 6.66588823, 6.1555186 , 5.35505711,
       5.07932047, 6.20786294, 5.21893484, 6.43001727, 5.2192625 ,
       5.32531268, 5.21835755, 5.05224599, 5.60678369, 5.0120603 ,
       6.17010025, 5.74020323, 6.37161258, 5.33865405, 6.06297922,
       5.73072649, 5.57753135, 5.18510358, 6.21179885, 5.53641

**Batch prediction**
 - after model development we pass a batch of  input
- in the above examples we are passing 480 observations/tuple at a time
- this is called as batch prediction 

**Real time or Endpoint prediction**
- after model development will pass a single observation
- it will give the  quick response
- so that  it is called as real time prediction

**note**
 - number of values we are passing in a list= number of columns
 - on how many columns your model trained, that many values only model consider.

In [30]:
LR.predict([[1,3,4,5,6,7,8,9,12,13,14,15]])

array([-156.24537161])

In [31]:
ip1=[1,2,3,4,5,6,7,8,9,10,11,13]
LR.predict([ip1])

array([-112.98273503])

In [41]:
LR.predict([[1,2,3,4,5,6,7,8,9,10,11,12]])

array([-113.28018132])

In [32]:
x_test.shape,y_test.shape,y_predictions.shape # 480 input
# 480 original output, 480 model output

((480, 12), (480,), (480,))

In [33]:
test_data=x_test
test_data['y_actual']=y_test
test_data['y_predictions']=y_predictions
test_data

index  fixed acidity  volatile acidity  citric acid  residual sugar  \
688    1377            7.7             0.660         0.04             1.6   
961    1923            7.1             0.560         0.14             1.6   
726    1453            8.1             0.720         0.09             2.8   
537    1075            8.1             0.825         0.24             2.1   
1544   3089            8.4             0.370         0.43             2.3   
...     ...            ...               ...          ...             ...   
1461   2923            6.2             0.785         0.00             2.1   
1591   3183            5.4             0.740         0.09             1.7   
1045   2091            6.9             0.440         0.00             1.4   
1498   2997            6.6             0.895         0.04             2.3   
42       85            7.5             0.490         0.20             2.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
688       0.039                  4.0                   9.0  0.99620  3.40   
961       0.078                  7.0                  18.0  0.99592  3.27   
726       0.084                 18.0                  49.0  0.99940  3.43   
537       0.084                  5.0                  13.0  0.99720  3.37   
1544      0.063                 12.0                  19.0  0.99550  3.17   
...         ...                  ...                   ...      ...   ...   
1461      0.060                  6.0                  13.0  0.99664  3.59   
1591      0.089                 16.0                  26.0  0.99402  3.67   
1045      0.070                 32.0                  38.0  0.99438  3.32   
1498      0.068                  7.0                  13.0  0.99582  3.53   
42        0.332                  8.0                  14.0  0.99680  3.21   

      sulphates  alcohol  y_actual  y_predictions  
688        0.47      9.4       5.0       5.160034  
961        0.62      9.3       5.0       5.319538  
726        0.72     11.1       6.0       5.636761  
537        0.77     10.7       6.0       5.526190  
1544       0.81     11.2       7.0       6.322058  
...         ...      ...       ...            ...  
1461       0.61     10.0       4.0       5.125442  
1591       0.56     11.6       6.0       5.526977  
1045       0.58     11.4       6.0       6.180853  
1498       0.58     10.8       6.0       5.237591  
42         0.90     10.5       6.0       5.720098  

[480 rows x 14 columns]

In [34]:
y_test.values

array([5., 5., 6., 6., 7., 5., 6., 5., 5., 6., 6., 5., 6., 6., 6., 5., 5.,
       5., 7., 5., 5., 6., 5., 5., 4., 6., 6., 5., 6., 6., 5., 6., 5., 5.,
       6., 5., 6., 5., 5., 6., 6., 7., 6., 7., 5., 5., 5., 5., 7., 5., 5.,
       7., 7., 7., 5., 5., 6., 5., 6., 5., 6., 5., 5., 6., 6., 7., 6., 7.,
       5., 6., 6., 6., 5., 7., 5., 5., 6., 7., 5., 6., 6., 5., 6., 5., 6.,
       5., 7., 5., 6., 5., 7., 5., 6., 5., 6., 5., 5., 7., 7., 6., 5., 5.,
       5., 6., 5., 5., 6., 4., 5., 6., 7., 5., 7., 6., 6., 6., 5., 5., 8.,
       6., 8., 6., 5., 6., 6., 5., 5., 6., 6., 7., 5., 5., 5., 5., 5., 6.,
       6., 5., 6., 5., 6., 5., 6., 6., 6., 6., 5., 6., 7., 5., 4., 6., 6.,
       7., 5., 6., 5., 5., 7., 7., 6., 6., 6., 6., 6., 6., 5., 5., 5., 6.,
       5., 5., 5., 6., 6., 6., 5., 7., 6., 5., 5., 3., 6., 6., 5., 5., 6.,
       6., 6., 7., 6., 6., 5., 7., 6., 5., 5., 7., 5., 5., 7., 6., 5., 6.,
       7., 6., 6., 5., 5., 3., 5., 5., 6., 6., 6., 7., 5., 5., 5., 6., 6.,
       6., 6., 5., 6., 5.

In [35]:
#y_test is a serires
#y_predictions is numpy array values
#y_predictions
print(y_test.values[:5])# float 5. means 5.0
print(y_predictions[:5])

[5. 5. 6. 6. 7.]
[5.16003375 5.31953766 5.63676143 5.52619018 6.32205835]


In [36]:
# MSE formula


- step1: we already has y_actual(y_test) data and y_predictions(model perdictions)
- step2: through a for loop will call each value, and subtract both
- step3: Square the subtractions and append in a list 
- step4: get the sum of all the values in a list 
- step5: Divide by len(y_test) or len(y_predictions)

In [37]:
for i in range(len(y_test)):
    print(y_test.values[i],y_predictions[i])

5.0 5.160033752979995
5.0 5.319537663475428
6.0 5.636761431803537
6.0 5.526190181045504
7.0 6.3220583494591285
5.0 5.371931254246308
6.0 5.371912104360295
5.0 5.918711491256875
5.0 5.460591737820401
6.0 7.048997779431611
6.0 4.8912127665479375
5.0 5.1791866267642455
6.0 5.7410638068858155
6.0 5.547362676439235
6.0 5.58388732148436
5.0 5.283181108210368
5.0 4.89286273827382
5.0 5.140019910547972
7.0 6.281887861808164
5.0 5.117684471686525
5.0 5.08506006069409
6.0 5.9102674298925315
5.0 5.156830019159157
5.0 5.462184104467434
4.0 5.695492077016809
6.0 6.277069053714923
6.0 5.328943589561378
5.0 5.536536692708802
6.0 6.046322394589836
6.0 5.462458406399534
5.0 4.690006244180175
6.0 6.182311945193991
5.0 5.2038137433750755
5.0 5.5988614186182595
6.0 5.595329877037267
5.0 5.541456883098602
6.0 6.3559181132225415
5.0 5.199354008244747
5.0 5.474220784130701
6.0 5.81405986121179
6.0 5.159017265575482
7.0 6.153683041269739
6.0 5.698028902065172
7.0 5.376798619321601
5.0 5.624565464895987
5.0 5.

In [38]:
for i in range(len(y_test)):
    print(y_test.values[i]-y_predictions[i]) #subtraction

-0.16003375297999511
-0.3195376634754279
0.36323856819646316
0.47380981895449636
0.6779416505408715
-0.3719312542463076
0.6280878956397054
-0.9187114912568752
-0.4605917378204012
-1.0489977794316108
1.1087872334520625
-0.17918662676424546
0.2589361931141845
0.452637323560765
0.41611267851564016
-0.2831811082103677
0.1071372617261801
-0.1400199105479718
0.7181121381918363
-0.11768447168652507
-0.08506006069409011
0.08973257010746849
-0.15683001915915717
-0.4621841044674344
-1.6954920770168087
-0.2770690537149232
0.6710564104386219
-0.5365366927088022
-0.046322394589836335
0.5375415936004657
0.3099937558198249
-0.18231194519399097
-0.20381374337507552
-0.5988614186182595
0.40467012296273275
-0.5414568830986024
-0.3559181132225415
-0.1993540082447467
-0.4742207841307007
0.1859401387882098
0.840982734424518
0.8463169587302612
0.30197109793482824
1.623201380678399
-0.6245654648959871
-0.00325407710598391
0.0983945694126227
-0.7579910755789818
0.647333135721091
-0.5611851561933463
0.10026901

In [39]:
for i in range(len(y_test)):
    v1=(y_test.values[i]-y_predictions[i])
    v2=v1**2
    s=s+v2
print(s/len(y_test))

NameError: name 's' is not defined

In [ ]:
v1=[(1,2),(3,5),(5,7)]# try own self
v2=(10,20)
# calculate the distance between each point in v1 with v2

**feature selection in regression problems**
- p_value concept
- H_o : there is no relation between independent variable and dependent variable
- H_a : there is a relation between independent variable and dependent variable
  
- p>alpha :  Not Reject the null hypothesis

**sklearn package will not give the p_value**
- so for p-value we need to  stats model package
- inside stats model we have ols method available

# Stats.OLS Method

In [ ]:
from statsmodels.api import OLS
ols=OLS(y_train,x_train).fit().summary()
ols

- based on alpha =0.05
- we will reject 3 columns : fixed acidity ,citric acid, Residual sugar 
- again we need to build the model by using other features

$Method -2$

**correlation between the features**

In [ ]:
cols=['fixed acidity','citric acid','residual sugar']
new_data=df.drop(cols,axis=1)
new_data

In [ ]:
corr=new_data.corr()


In [ ]:
sns.heatmap(corr,annot=True)

- from above  correlation
- total sulphar diioxide and free sulpher dioxide are high postive correalted
- 0.667
- we can use any one of the column
- remove the column which is having less relation with target data


In [ ]:
new_data.columns

In [ ]:
col1=new_data['free sulfur dioxide']
col2=new_data['total sulfur dioxide']
plt.scatter(col1,col2)

**Method 3**

$variance threshold method$
- some time columns values are not vary much 
- for example in loan perdiction data: we have a column loan trem 360
- the data is not vary across , then we can remove those column
- every data has some variance available
- if the variance is zero means the data is not varying
- the data has most of the time only one value is there
- it is available sklearn.feature selection

# save the model

In [ ]:
-  once model developed we need to save the model 
- that model can use by any one 
- model we, can save in different formats
    - pickle .pkl
    - joblib .joblid
    - save(in deep learning)

In [77]:
import pickle
pickle.dump(LR,
           open("linear_wine_model.pkl",'wb'))
#model name=lR
# in which name the model is saving: linear_wine_model 
#extenstion 

In [78]:
model=pickle.load(open('linear_wine_model.pkl','rb'))
model

LinearRegression()

In [80]:
model.predict([[1,2,3,4,5,6,7,8,9,10,11]])

array([-82.48338949])

In [ ]:
x_test.to_csv